npm/npm-expansions

- index.json
> Node Pleases Me

- index.json
Lets mixin some of that good ol java feuding :p
> Add nose pickers maven

- index.json
Something I thought of while driving home. I felt inspired enough to figure out where these expansions were stored and submit a pull request.
> Narcoleptic Pony Machine

- index.json
> New Power Management

- index.json
> Ninja Pokemon Master

- index.json
> North Pole Merriment

- index.json
i have no idea what's going on - it didn't look that way in vim :innocent:
> nuǝɯ pǝɥsᴉꞁod mǝu

- index.json
I suggest Norse Polytheistic Mythology!
>  Norse Polytheistic Mythology

- index.json
because [npm-expansions looks like a list of photography topics waiting to happen!](https://twitter.com/shimaore29/status/545628644522356736)
> Add "NPM-Expansions Photographs Meme"

- index.json
> Now Playing Mario

- index.json
> added my personal mucus (Nourished Personal Mucus)

- index.json
not sure if this is worth worrying about, but it does make it easier to see what's been done already
> sort expansions alphabetically

- index.json
Removed one of "No Possible Meaning". In fact I don't know if this was intended, but there were included by #169 and #188 :smile:
> Removed duplicate

- index.json
Currently procrastinating by checking out neat packages that have nothing to do with what I should be working on right now.  Discovered this amazing repo.  Seemed appropriate.
> Nifty Procrastination Machine

- index.json
> Who needs skynet when we have NPM!

- index.json
Adds "Needy Poetic Mothers" to the list! :)
> Needy Poetic Mothers+

- index.json
Add Naughty Programmers Madness
> Add Naughty Programmers Madness

- index.json
The day programmers forget everything, the Naked Programmers Monday
> Add 1 expansion - Naked Programmers Monday

- index.json
> Nagging Penguin Matriarchs

- index.json
> Added "Nerdy Programmers Mingling"

- index.json
NPM and I can has chemistry?
```
Np
Pm
Mn
Np........[N]eptunium
Pm.......[P]romethium
Mn......[M]anganese
Np
Pm
Mn
```
All three are [N]otably [P]aramagnetic [M]etals.
All three are shiny, contains 7 electrons in outermost shell, and cool sounding.
> Neptunium, Promethium, Manganese

- index.json
> Ni Pin Ming is Chinese funny word 你拼命 stands for NPM

- index.json
> Add Nuclear-Powered Malevolence

- index.json
@othiym23 I'm in ur github issues hasslin' ya.
> Add "Norvell, Please Merge"

- index.json
Just thought "Neutron Polarization Manipulator" would be a nice acronym
> Added "Neutron Polarization Manipulator"

- index.json
> Fixed broken JSON

- index.json
My sugestion: "notable peru mariachis"
> "Notable Peru Mariachis"

- index.json
> Node Pokiest Mechanism

- index.json
The last suggestion for today.
> with NPM, we "Need Pray More".

- index.json
> nonsense placement mandatory

- index.json
"No Particular Method",
"Not Parents' Money"
> Added 2 NPM expansions

- index.json
> Naughty pterodactyl maid

- index.json
You were missing one... just one: Nude Poltergeist Monarch
> Nude Poltergeist Monarch

- index.json
> Neural Prediction Model!

- index.json
https://twitter.com/seldo/status/576131746409811969
> Next Popular Module

- index.json
> Naive Puppets Marching

- index.json
Well *somebody* has to monitor them!
http://bit.ly/nimble_pirate_monitor
> Nimble Pirate Monitor

- index.json
> Nananananananananananananananana.. Pat Man!

- index.json
Not sure this is allowed but doing it anyway
> next() Packaged Middleware

- index.json
> Notable Pastry Maker

- index.json
Well, not that funny, but (somehow) true
> New NPM expansion: Novel Planetary Movement

- index.json
SHUT DOWN EVERYTHING!
[http://knowyourmeme.com/memes/shut-down-everything](http://knowyourmeme.com/memes/shut-down-everything)
> Notify President Madagascar

- index.json
> Added "Notorious Public Menace"

- index.json
> Now Packing Magic!

- index.json
> Naps Per Month!

- expansions.txt
added 2 new expansions: Native Package Master and Nobody Publish Monsters
> added 2 new expansions

- expansions.txt
> Ahhhhhh yeaaaaaaahhhh.

- expansions.txt
The word "nomenclature" is neat.
> Add 'Nomenclature Processing Machine'

- expansions.txt
> never propel marmalade

- expansions.txt
Added the "Nautical Pirate Moustache" addition.
> Nautical Pirate Moustache

- expansions.txt
> Pokemon → Pokémon

- expansions.txt
Have some culture:
http://en.wikipedia.org/wiki/Pontifex_Maximus
> Added Nepotistic Pontifex Maximus

- expansions.txt
> Added Novelty Plastic Moustache

- expansions.txt
> Added "Natural Polyglot Machine" to expansion list

- expansions.txt
> npm packaged modules

- expansions.txt
this one should be better than the midgets one i put up earlier. sorry for that
> add 'not pictured: mangoes'

- expansions.txt
Many programmers like working at night, as it is quiet and there are no disturbances. Thus, they are more productive during nights. Thus, nights pay more.
> Added "Nights Pay More"

- expansions.txt
And reverted Nude Pacifist Maid commit.
> Added Nonsense Poetry Manager

- expansions.txt
> Neatly Punctuated Musings

- expansions.txt
> Normal Programming Mistake

- expansions.txt
I considered "Neat-o", but it didn't quite look right.
> Add "Neato Polyester Material"

- expansions.txt
Add the phrase,
Neverending Programming Mistakes.
> Add Neverending Programming Mistakes

- expansions.txt
I have read these little snippets in the NPM header for so long but never realized I could contribute.
> add Napolean Paced Mischeviously

- expansions.txt
At least most of my use is at night.
> Nocturnal Programmer's Mate

- expansions.txt
> Adds Ninja Parading Musically to expansions.txt

- expansions.txt
See what you meant on Nutritious Pearly Milk - how's this instead?
> Added Nutrient Packed Morsels

- expansions.txt
> Added Necromancers Playing MTG

- expansions.txt
> Nobody Picked Me

- expansions.txt
> Node's Package Magician

- expansions.txt
> new expansion added

- expansions.txt
> npm extension

- expansions.txt
Think it fits the criteria well enough.
> Added Neo's Personal Matrix

- expansions.txt
Adds Noncommital Premarital Mischief
> Needlessly Propositioned Maintenance

- expansions.txt
I think this is a misspelling of "patriotic"
> fixed patriotic spelling error

- expansions.txt
Could also be Nine P.M. but not sure if abbreviations are allowed.
> Nine Post Meridiem

- expansions.txt
> nested partial modules

- README.md
Avoid mixing cases in the bulleted list.
Went with capitals, because the phrases end with periods.
> Don't mix cases in README

- expansions.txt
I wonder why there are not any internet slang in here. Is internet slang acceptable? Or you prefer words without numbers (like Noob Pwn Me). Or this is not acceptable at all?
> N00b Pwn M3

- expansions.txt
> Nodding Personal Monks

- expansions.txt
> Noxious Plant Miasma

- expansions.txt
Added Nitrogen Poisonous Monoxide to expansions.txt
> Nitrogen Poisonous Monoxide

- expansions.txt
Alternative that avoids use of Now
> NASA: Pluto Matters!

- expansions.txt
> Novices Performing Miracles

- expansions.txt
> new entry: Newly Practicing Mortician

- expansions.txt
> Node's Power Meal

- expansions.txt
> Nostalgic Pizza Manager

- expansions.txt
Revised spelling per LV tip.. :)
> l'orthographe révisée

- expansions.txt
A silly expansion, refering to my experience in the newer JS environments and libraries.
> New suggestions

- expansions.txt
Because gardening terms are fun! :bouquet:
> Add "Noctiflorous Pansy Mulch" to expansions.txt

- expansions.txt
> And yet there's more -- in public!

- expansions.txt
"Neovictorian" can be counted as one word, right?
> Neovictorian Paisley Menswear

- expansions.txt
I am not affiliated with the Milk Marketing Board or any of its members.
> Suggested Note: Purchase Milk

- expansions.txt
Another way of helping you remember how to spell 'npm'.
> Suggested Nth Phonetic Mnemonic

- expansions.txt
Notwithstanding [Perlito](http://www.perlito.org/)'s miracles
> Suggested Needs Perl Modules

- expansions.txt
You were right; this version is much better.
> Negatory. Postpone Mission.

- expansions.txt
This could be changed to "mankind", but I thought "man" sounded more poetic.
> Nature Preceded Machines

- expansions.txt
Well who really knows the difference anyway? :-)
> Noodly Pasta Maker

- expansions.txt
> And till there's more

- expansions.txt
> No princess mario

- expansions.txt
Adds "Nettle Pie Market" to extensions.txt
> Nettle Pie Market

- expansions.txt
> Nothing Prevents Misery

- expansions.txt
> Neutrino Packing Machine

- expansions.txt
onomatopoeia.js
:horse: :cat: :cow:
:horse_racing: :cat2: :cow2:
> Neigh Purr Moo

- expansions.txt
Because the npm repository is kind of a haystack
> Needle-Pinpointing Machine

- expansions.txt
> negligent pachinko machines 

- expansions.txt
Adding NuGet Package Manager to the list.
> NuGet Package Manager

- expansions.txt
> Not Pancake Mix

- expansions.txt
**Nimble** *quick and light in movement or action; agile*
**Package** *an object or group of objects wrapped in paper or packed in a box*
**Maestros** *a distinguished figure in any sphere*
> Suggest 'Nimble Package Maestros' for random n-p-m definition

- expansions.txt
Who manages the puma managers?
> Needs Puma Managers

- expansions.txt
> Nice Poutine Meal

- expansions.txt
Think *We Can Remember It for You Wholesale*.
> Newly Purchased Memories

- expansions.txt
Promotes or prefers would also work.
> npm Promulgates Marsupials

- expansions.txt
Are we not drawn onward, we few, drawn onward to new era?
No pet so tragic as a cigar to step on.
Never odd or even.
> Nondeterministic Palindrome Machine

- expansions.txt
"Package" isn't particularly creative, but I like the idea of an ancient shark politely providing modules
> Neighborly Package Megalodon

- expansions.txt
added "Nuptial Predicament Mediation"
> Nuptial Predicament Mediation

- expansions.txt
added "Novice, Paragon, Master"
> Novice, Paragon, Master

- expansions.txt
> Neatly Placed Mail

- expansions.txt
> Newly Potted Mandrakes

- expansions.txt
> Add "Needlessly Provoking Marsupials".

- expansions.txt
It's better to node on a Noiseless Peaceful Morning !
> Noiseless Peaceful Morning !

- expansions.txt
adding some nonstop pajama model action.
> Nonstop Pajama Models

- expansions.txt
[Naan and Paneer Makhani](http://www.ecurry.com/blog/wp-content/uploads/2011/03/Paneer-Makhani-4-465x620.jpg)
> Add "Naan and Paneer Makhani"

- expansions.txt
> Added new propositions

- expansions.txt
> Add "Naturally Pacifist Marsupials"

- expansions.txt
Because there's not enough Limp Bizkit here.
> Added Nü Metal Provocateur

- expansions.txt
"Nondigestible Purple Mayonnaise" added to /expansions.txt
> Added Nondigestible Purple Mayonnaise

- expansions.txt
> Nightly Piano Man

- expansions.txt
The [galaxy](https://en.wikipedia.org/wiki/Messier_83), that is.
> Nebulae Populate M83

- README.md
See commit 96580b87033acb201cb6fa935c6d85d092db7f54
> Removed questionable expansion from README

- expansions.txt
I added "Non Polar Magnetism". I like it because its impossible, or the ultimate key to UFO technology.
> Non Polar Magnetism

- expansions.txt
Added my own and repositioned my muse, "nuǝɯ pǝɥsᴉꞁod mǝu", such that mine could fit logically into the alphabetical order.
> ɹǝʞɐW ǝʌᴉʇɔǝdsɹǝԀ ʍǝN

- expansions.txt
> Nashville Plays Music

- expansions.txt
I thought this was ironic and funny, hopefully others will find this funny too.
> my first of hopefully many contributions to npm

- expansions.txt
I was at Node Interactive and got an umbrella from the NPM booth. Thought this was fitting :smile:
> Nullifying Precipitation Machine

- README.md
Removing "No", "New" and "Never" from the "Be novel" section to align with the new "No More Please" section.
> align text with 'no more please' section

- expansions.txt
I'll get around to fixing the "New Perspective Maker" maybe eventually probably, but I thought of this one, personally liked it better, and written this way it doesn't require an exception. So... cool.
> naM ,sevitcepsreP weN

- expansions.txt
> Neat Pidgeon Poop

- expansions.txt
Once every leap year, time travelers converge on Nantes to trade in strange loops, grandparent paradoxes, and anachronisms.
> Proposing the Nantes Paradox Market

- expansions.txt
Although, in no way we really believe that `npm` is ANY kind of mockery. right?
> Novel Preposterous Mockery

- expansions.txt
> Nicely Printed Maps

- expansions.txt
Always causing trouble for the establishment
> Add Nascent Political Miscreant

- expansions.txt
> Nanometers Per Millisecond

- expansions.txt
> Naturally Processed Meals

- expansions.txt
> Narcissistic Project Managers

- expansions.txt
> Network Performance Monitor

- expansions.txt
> Noiseless Praying Mantis

- expansions.txt
> Nonstop Perpetual Motion

- expansions.txt
> Nothing Plus More

- expansions.txt
> Novice, Practiced, Mastered

- expansions.txt
> Never Please Meanies

- expansions.txt
Basically, it's a tasty, drinkable (potable) moonshine. :droplet:
> Nonalcoholic Potable Moonshine

- expansions.txt
It's how she keeps her skin so soft. :lipstick:
> Nefertiti's Private Moisturizer 

- expansions.txt
This is what I called my brother back in the 90's...
> Nintendo Playing Mastermind

- expansions.txt
It's ironic because Nosferatu is undead.
> Nosferatu's Pace Maker

- expansions.txt
> Nutella with Pepperoni and Mushrooms

- expansions.txt
> NeXTSTEP Programming Mastermind

- expansions.txt
Thought this one was fitting.
Thanks,
BC
> Adding Needful Program Management

- expansions.txt
> Proposing Nominal Package Missing 😄

- expansions.txt
> No Padding Module

- expansions.txt
> Adds npm's personal messenger

- expansions.txt
Node's Perfect Mate - surprised it wasn't there already
> Added Expansion

- expansions.txt
"Não posso mais" means "I cannot anymore/I can't take it anymore" in Portuguese
> Adds the very first Portuguese extension

- expansions.txt
https://github.com/mozilla/nunjucks is a JavaScript templating engine
Also at https://www.npmjs.com/package/nunjucks of course :wink:
> Nunjucks Powers Mozilla

- expansions.txt
> Nefarious Pickle Muncher

- expansions.txt
> Neo's Playing Morpheus

- expansions.txt
Or maybe some of these are better?
- Numeric Pivot Mistake
- Negative Point Mistake
- Negative Positioning Mistake
- Negatively Proportioned Menu
> nuǝW pǝuoᴉʇᴉsoԀ ʎlǝʌᴉʇɐƃǝN (Negatively Positioned Menu) + alternatives

- expansions.txt
> added new expansion "Nasal Piercings Manipulator"

- expansions.txt
Fix merge conflicts from previous PR - 
https://github.com/npm/npm-expansions/pull/1157#issuecomment-225748052
> Re-Submit "Necessarily Precedes Mischief"

- expansions.txt
to fix conflicts from previous PR - 
https://github.com/npm/npm-expansions/pull/1160#issuecomment-225747991
> Re-Submit "Notwithstanding Precautions, Misadventure"

- expansions.txt
it appears there was some Notorious Merging Problem
> Added new expansion - Nasal Piercings Manipulator

- expansions.txt
Replaces #1098 due to a conflict
> Nearly Perfected Mystique

- expansions.txt
> adds national puppy menace 🐶🔥

- expansions.txt
Re submitting after removing conflicts
> Neurosis Prevention Mechanism

- expansions.txt
Rats, beaten to "nitpicking".
Re-submitting as requested in previous [PR 1145](https://github.com/npm/npm-expansions/pull/1145)
> Add Nitpicking Magistrate

- expansions.txt
```
O       o O       o O       o
| O   o | | O   o | | O   o |
| | O | | | | O | | | | O | |
| o   O | | o   O | | o   O |
o       O o       O o       O
```
> Add "Nucleic Phosphate Modifier"

- expansions.txt
Re submitting due to spelling mistake in #1140
> NASA Planetary Mission

- expansions.txt
let's add some funk to this list! :notes:
> Added "Notes Per Minute"

- expansions.txt
Based on the International Telecommunications Union Standard Phonetic Alphabet.
Coding has a great history in telecommunications, let's honor it!
> Add `npm` expressed as standard phonetic alphabet

- expansions.txt
> Need Public Method

- expansions.txt
Added Neighbour Problem Manager to expansions.txt
> Neighbour Problem Manager

- expansions.txt
> NORWEGIAN PUFFIN MOVIES.

- expansions.txt
Because who doesn't love mangoes 😄
> Add Newly Picked Mango as npm

- expansions.txt
> Remove two objectionable expansions

- expansions.txt
> feat(exp): add National Preventative Mechanism

- expansions.txt
> Add an expansion

- expansions.txt
Add "Natty Precise Maverick"
(Ubuntu version names)
> Add "Natty Precise Maverick"

- expansions.txt
Adding Nevermore: a Poet's Mantra. Was debating between this and Nevermore: Poe's Mantra
> Nevermore: a Poet's Mantra

- expansions.txt
One can never have too many nitroglycerin pickles...
> Nitroglycerin Pickle Machine

- expansions.txt
> added Nonstick Pancake Maker

- expansions.txt
Notwithstanding Previous Misdemeanors
> Add expansion

- expansions.txt
> Nature's Powerful Meme

- expansions.txt
It means "I need to code more" in Spanish
> Add Necesito Programar Más (I need to code more)

- expansions.txt
> Polymer nanocomposites are nanoparticles arranged / dispersed in a polymer matrix. 
Useful for new tissue engineering... or just a space-age sounding name :space_invader:
> Nano Particle Matrix

- expansions.txt
This PR adds "Neuron Powered Motorization" and "Nearly Post-Money". Opened a PR at @seldo's [request](https://twitter.com/seldo/status/986045514448756737). ✨
> Add Neuron Powered Motorization and Nearly Post-Money

- expansions.txt
`npm test` reordered a bunch, but only added `Need Paper Mache` because we can all use a little more paper mache in our lives
> Need Paper Mache

- expansions.txt
- package-lock.json
- Added "Neoclassical Philosophic Musings"
- Ran npm test - seems like it hadn't been run for a while
> Neoclassical Philosophic Musings

- expansions.txt
Removed duplicate: "Nonsense Parser Microframework"
> nonprofit-pizza-maker

- expansions.txt
Makes sense. Pluto is kinda useless and Elon is trying to colonize Mars. Wars gonna war. Nukes gonna nuke.
> Add Nuke Pluto and Mars

- expansions.txt
Suggestion to expand expansions.txt with "Neptune's Potato Monsters"
> Neptune's Potato Monsters

- expansions.txt
[It's a thing, apparently.](https://twitter.com/PooMuseum)
> National Poo Museum

- expansions.txt
> Nerfed Poet Melancholia

- expansions.txt
A Nephrite Power Mace would be heavy, but full of magic.
> Nephrite Power Mace

- expansions.txt
> Updated Expansions.txt

- expansions.txt
Because very old prancing minotaurs.
> Add "Neolithic Prancing Minotaurs"

- expansions.txt
> Nostalgic Punchcard Missing

- expansions.txt
Thanks to Brandon for the idea :)
> Added `Non-Production Machines`

- expansions.txt
Who is this pomegranate magnate, and what are they planning??
> Add "Nefarious Pomegranate Magnate"

- expansions.txt
- added "NASA's Punk Music" to expansions.txt file.
> add NASA's Punk Music

- expansions.txt
> Numbers Produce Meaning

- expansions.txt
- package-lock.json
🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞🥞
> Numerous Pancakes Munched

- expansions.txt
> add 'Natively Pluggable Module'

- expansions.txt
> add 'Naive Props Mutation'

- expansions.txt
> add 'Negotiate Pushing Milestone'

- expansions.txt
> add 'Nervously Practice Multithreading'

- expansions.txt
- package-lock.json
* Added a new Phrase in [Expansions.txt](https://github.com/npm/npm-expansions/blob/master/expansions.txt), 'Nahi Pata Mujhe!' (which means 'I don't know!' in Hindi), at line 17.
> Added 'Nahi Pata Mujhe!'(means 'I don't know!' in Hindi) at line 17

- expansions.txt
> add Nutella Pancake Machine

- expansions.txt
Yes, we are newborn and we are monsters.
> Newborn Programming Monsters: NPM

- expansions.txt
they lose their waterproofing during this process and are landbound
> Nesting Penguins Molt

- .travis.yml
- README.md
i assumed we turned this off because we get so many PRs that it clogs up our public travis queue. removing stuff so it's not confusing
> fix(test): remove travis stuff since we do not use travis for this

- expansions.txt
Adding expansion
> Newman's Personal Motorcade
> Newman's Personal Motorcade

- expansions.txt
Just ran npm test and observed the ordering issue to thought of submitting a PR
> Ran Test and Reordered

- expansions.txt
> feat: "Navigator Prefabricating Marinates"

- expansions.txt
Removing "niggling pants monkey"; per the README:
> Avoid anything that even slightly hints of violating npm's [code of conduct](https://www.npmjs.com/policies/conduct/). These are literally the first words that appear on the website, and our audience is very broad, so it's best to avoid things that can be misconstrued.
And there's a lot to potentially misconstrue here, as I was reminded by a user who saw this.
Since I wouldn't want to remove something without also restoring balance to the universe, I offer you "ninety proof mezcal".
> Ninety proof mezcal

- expansions.txt
This is a great Spanish expansion.
Literally this translates to "Node allows a lot"; but Spanish speakers will understand it as "you can do a lot with Node."
> Node Permite Mucho

- expansions.txt
neptunes prized moon
its neptune's most prized moons!
🤷‍♀️
> Neptune's Prized Moons

- expansions.txt
> Ninja Painter Michelangelo
